	IMPORT loadcart
	IMPORT vrom_req
	IMPORT map89_
	IMPORT mapAB_
	IMPORT mapCD_
	IMPORT mapEF_
	IMPORT map89AB_
	IMPORT mapCDEF_
	IMPORT map89ABCDEF_
	IMPORT chr0_
	IMPORT chr1_
	IMPORT chr2_
	IMPORT chr3_
	IMPORT chr4_
	IMPORT chr5_
	IMPORT chr6_
	IMPORT chr7_
	IMPORT chr01_
	IMPORT chr23_
	IMPORT chr45_
	IMPORT chr67_
	IMPORT chr0123_
	IMPORT chr4567_
	IMPORT chr01234567_
	IMPORT updateBGCHR_
	IMPORT updateOBJCHR
	IMPORT mirror1_
	IMPORT mirror2H_
	IMPORT mirror2V_
	IMPORT mirror4_
	IMPORT chrfinish
	END
