	IMPORT void
	IMPORT empty_R
	IMPORT empty_W
	IMPORT ram_R
	IMPORT ram_W
	IMPORT sram_R
	IMPORT sram_W
	IMPORT sram_W2
	IMPORT rom_R60
	IMPORT rom_R80
	IMPORT rom_RA0
	IMPORT rom_RC0
	IMPORT rom_RE0
	IMPORT filler_
	IMPORT memset16
	IMPORT memset32
	IMPORT memcpy32
	IMPORT memset16_
	IMPORT memset32_
	IMPORT memcpy32_
	END
